// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcnojeouypwbkkbnbold.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjbm9qZW91eXB3YmtrYm5ib2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MzE1NzksImV4cCI6MjA4NjAwNzU3OX0.gzDiiHDrr7vaoo7GFW77t_sjnsppKL5R3H8rY3fNWpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});